## Assignment 2.1
Create a 2D random tensor `x1` of shape (5, 6) and print its shape, dtype, and mean.

In [10]:
import torch

# Create a 2D random tensor X1 of shape (5, 6)
x1 = torch.randn(5, 6)

print("Shape:", x1.shape)
print("Dtype:", x1.dtype)
print("Mean:", x1.mean().item())

Shape: torch.Size([5, 6])
Dtype: torch.float32
Mean: 0.1937534064054489


## Assignment 2.2
Create an integer tensor `x2` of shape (4, 4) with random values in [0, 10), convert it to float, and show the difference.

In [11]:
# Create an integer tensor X2 of shape (4, 4) with values in [0, 10)
x2 = torch.randint(0, 10, (4, 4), dtype=torch.int32)
x2_float = x2.float()

diff = x2_float - x2
print("X2:\n", x2)
print("X2_float:\n", x2_float)
print("Difference (X2_float - X2):\n", diff)

X2:
 tensor([[6, 5, 8, 6],
        [8, 4, 6, 1],
        [9, 1, 8, 0],
        [5, 6, 3, 8]], dtype=torch.int32)
X2_float:
 tensor([[6., 5., 8., 6.],
        [8., 4., 6., 1.],
        [9., 1., 8., 0.],
        [5., 6., 3., 8.]])
Difference (X2_float - X2):
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


**Explanation**
Converting small integers to float preserves exact values, so `x2_float - x2` is all zeros.

## Assignment 2.3
Create a random float tensor `x3` of shape (3, 2), transpose it, and compute `x3 @ x3_t`.

In [12]:
# Create a random float tensor X3 of shape (3, 2)
x3 = torch.randn(3, 2)
x3_t = x3.T

result = x3 @ x3_t
print("Result shape:", result.shape)

Result shape: torch.Size([3, 3])


## Assignment 2.4
Create two integer tensors `x4_a` and `x4_b` of shape (2, 3) with values in [1, 5), then compute element-wise add, subtract, and multiply.

In [13]:
# Create integer tensors X4_A and X4_B of shape (2, 3) with values in [1, 5)
x4_a = torch.randint(1, 5, (2, 3), dtype=torch.int32)
x4_b = torch.randint(1, 5, (2, 3), dtype=torch.int32)

add_res = x4_a + x4_b
sub_res = x4_a - x4_b
mul_res = x4_a * x4_b

print("X4_A:\n", x4_a)
print("X4_B:\n", x4_b)

print("X4_A + X4_B:\n", add_res)
print("Shape:", add_res.shape)

print("X4_A - X4_B:\n", sub_res)
print("Shape:", sub_res.shape)

print("X4_A * X4_B:\n", mul_res)
print("Shape:", mul_res.shape)

X4_A:
 tensor([[3, 1, 3],
        [1, 2, 1]], dtype=torch.int32)
X4_B:
 tensor([[1, 4, 3],
        [4, 4, 4]], dtype=torch.int32)
X4_A + X4_B:
 tensor([[4, 5, 6],
        [5, 6, 5]], dtype=torch.int32)
Shape: torch.Size([2, 3])
X4_A - X4_B:
 tensor([[ 2, -3,  0],
        [-3, -2, -3]], dtype=torch.int32)
Shape: torch.Size([2, 3])
X4_A * X4_B:
 tensor([[3, 4, 9],
        [4, 8, 4]], dtype=torch.int32)
Shape: torch.Size([2, 3])


## Assignment 2.5
Create `x5` with `torch.linspace(1, 12, steps=12)`, reshape to (3, 4), flatten, and print shapes.

In [14]:
# Create X5 with linspace and reshape to (3, 4)
x5 = torch.linspace(1, 12, steps=12).reshape(3, 4)
x5_flat = x5.flatten()

print("Original shape:", x5.shape)
print("Flattened shape:", x5_flat.shape)

Original shape: torch.Size([3, 4])
Flattened shape: torch.Size([12])


## Assignment 2.6
Create a random float tensor `x6` of shape (4, 4), compute row-wise and column-wise sums, and confirm their shapes.

In [15]:
# Create a random float tensor X6 of shape (4, 4)
x6 = torch.randn(4, 4)

col_sum = x6.sum(dim=0)
row_sum = x6.sum(dim=1)

print("Column-wise sum:\n", col_sum)
print("Shape:", col_sum.shape)

print("Row-wise sum:\n", row_sum)
print("Shape:", row_sum.shape)

Column-wise sum:
 tensor([-0.5081,  2.5963, -3.5060,  0.1676])
Shape: torch.Size([4])
Row-wise sum:
 tensor([ 0.0458, -0.9567,  0.6203, -0.9596])
Shape: torch.Size([4])


## Assignment 2.7
Create random float tensors `x7_a` and `x7_b` of shape (2, 2), then concatenate along dimensions 0 and 1.

In [16]:
# Create two random float tensors X7_A and X7_B of shape (2, 2)
x7_a = torch.randn(2, 2)
x7_b = torch.randn(2, 2)

concat_dim0 = torch.cat([x7_a, x7_b], dim=0)
concat_dim1 = torch.cat([x7_a, x7_b], dim=1)

print("X7_A:\n", x7_a)
print("X7_B:\n", x7_b)

print("Concat dim=0 (shape 4x2):\n", concat_dim0)
print("Concat dim=1 (shape 2x4):\n", concat_dim1)

X7_A:
 tensor([[-1.1302,  0.9590],
        [-0.0175,  1.2760]])
X7_B:
 tensor([[ 0.3286,  0.6048],
        [ 1.5347, -0.0497]])
Concat dim=0 (shape 4x2):
 tensor([[-1.1302,  0.9590],
        [-0.0175,  1.2760],
        [ 0.3286,  0.6048],
        [ 1.5347, -0.0497]])
Concat dim=1 (shape 2x4):
 tensor([[-1.1302,  0.9590,  0.3286,  0.6048],
        [-0.0175,  1.2760,  1.5347, -0.0497]])


## Assignment 2.8
Create a 3D random tensor `x8` of shape (2, 3, 4), find the max, and compute the mean along dimension 2.

In [17]:
# Create a 3D random tensor X8 of shape (2, 3, 4)
x8 = torch.randint(0, 10, (2, 3, 4), dtype=torch.int32)

max_val = x8.max()
mean_dim2 = x8.float().mean(dim=2)

print("Max value:", max_val.item())
print("Max value shape:", max_val.shape)
print("Mean along dim=2 shape:", mean_dim2.shape)

Max value: 9
Max value shape: torch.Size([])
Mean along dim=2 shape: torch.Size([2, 3])


## Assignment 2.9
Create a random float tensor `x9` of shape (3, 3) and compute its determinant.

In [18]:
# Create a random float tensor X9 of shape (3, 3)
x9 = torch.randn(3, 3)

det_val = torch.linalg.det(x9)
print("Determinant:", det_val.item())

Determinant: 0.05583071708679199


**Explanation**
The determinant measures how close the matrix is to being singular; values near zero indicate near-singularity.

## Assignment 2.10
Create `x10` with shape (3, 2), stack it 3 times along a new dimension, and print the final shape.

In [19]:
# Create a random float tensor X10 of shape (3, 2)
x10 = torch.randn(3, 2)

stacked = torch.stack([x10, x10, x10], dim=0)
print("Final shape:", stacked.shape)

Final shape: torch.Size([3, 3, 2])
