# Neural Network Classification – Assignments (Part 1: Basic PyTorch)

This notebook contains **Assignments 1–10** exactly following the provided lecture slides (Part 1: Basic PyTorch).

> Tip: Run cells from top to bottom.



In [ ]:
import torch

## 2.1 Assignment 1

**Instruction**
1. Create a **2D random** tensor `X1` of shape `(5, 6)` with `torch.randn`.
2. Print:
   - The **shape** of `X1`
   - The **data type** of `X1`
   - The **mean** of all elements in `X1`


In [ ]:
# Assignment 1
X1 = torch.randn(5, 6)

print("X1 shape:", X1.shape)
print("X1 dtype:", X1.dtype)
print("X1 mean:", X1.mean())
print("X1 mean:", X1.mean().item())



print("X1 mean (axis=0):", X1.mean(dim=0))
print("X1 mean (axis=1):", X1.mean(dim=1))
X1


X1 shape: torch.Size([5, 6])
X1 dtype: torch.float32
X1 mean: tensor(0.1450)
X1 mean: 0.14500778913497925
X1 mean (axis=0): tensor([ 0.1390, -0.2610,  0.9737,  0.0487, -0.2213,  0.1910])
X1 mean (axis=1): tensor([-0.4990,  0.3291,  0.3592,  0.2045,  0.3312])


tensor([[ 0.4048, -1.3543, -0.4976,  0.4747, -2.5095,  0.4880],
        [ 0.7846,  0.0286,  1.7423, -1.3527,  0.2191,  0.5526],
        [-0.1853,  0.7528,  1.0131, -0.3308,  0.5177,  0.3878],
        [-0.5797, -0.1691,  1.9312,  1.0119, -0.4752, -0.4920],
        [ 0.2704, -0.5628,  0.6793,  0.4405,  1.1415,  0.0186]])

In [11]:
# Assignment 1
X1 = torch.randn(2, 3, 4)
print(X1)
print("X1 shape:", X1.shape)
print("X1 dtype:", X1.dtype)
print("X1 mean:", X1.mean().item())



print("X1 mean (axis=0):", X1.mean(dim=0))
print("X1 mean (axis=1):", X1.mean(dim=1))
print("X1 mean (axis=2):", X1.mean(dim=2))

tensor([[[ 0.0733,  0.8187,  1.4805,  0.3449],
         [-1.4241, -0.1163, -0.9727,  0.9585],
         [ 0.0249, -0.3460,  0.2868, -0.7308]],

        [[ 0.1748, -1.0939,  0.9633, -0.3095],
         [ 1.2888,  0.0523, -1.5469,  0.7567],
         [ 0.7755,  2.0265,  0.9812, -0.6401]]])
X1 shape: torch.Size([2, 3, 4])
X1 dtype: torch.float32
X1 mean: 0.15943187475204468
X1 mean (axis=0): tensor([[ 0.1240, -0.1376,  1.2219,  0.0177],
        [-0.0676, -0.0320, -1.2598,  0.8576],
        [ 0.4002,  0.8403,  0.6340, -0.6855]])
X1 mean (axis=1): tensor([[-0.4420,  0.1188,  0.2649,  0.1908],
        [ 0.7464,  0.3283,  0.1326, -0.0643]])
X1 mean (axis=2): tensor([[ 0.6793, -0.3887, -0.1913],
        [-0.0663,  0.1377,  0.7858]])


## 2.2 Assignment 2

**Instruction**
1. Create an **integer** tensor `X2` of shape `(4, 4)` with random integers in `[0..10)`.
2. Convert it to **float** and store in `X2_float`.
3. Show the **difference** `(X2_float - X2)` and explain why the difference is zero or non-zero.


In [ ]:
# Assignment 2
X2 = torch.randint(low=0, high=10, size=(4, 4), dtype=torch.int64)
X2_float = X2.float()

diff = X2_float - X2
print("X2:", X2)
print("X2_float:", X2_float)
print("Difference (X2_float - X2):", diff)

X2_2 = X2_float.clone()
X2_2[0][0] = X2_2[0][0] + 0.5
diff2 = X2_2 - X2
print("Modified X2_2:", X2_2)
print("Difference after modification (X2_2 - X2):", diff2)
diff2 = diff2.int()
print("Difference after conversion to int:", diff2)

# Explanation:
# Converting int -> float preserves the exact integer values (for small ints like 0..9),
# so the difference is typically all zeros.


X2: tensor([[2, 3, 3, 1],
        [6, 4, 6, 9],
        [4, 8, 9, 2],
        [5, 9, 9, 6]])
X2_float: tensor([[2., 3., 3., 1.],
        [6., 4., 6., 9.],
        [4., 8., 9., 2.],
        [5., 9., 9., 6.]])
Difference (X2_float - X2): tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Modified X2_2: tensor([[2.5000, 3.0000, 3.0000, 1.0000],
        [6.0000, 4.0000, 6.0000, 9.0000],
        [4.0000, 8.0000, 9.0000, 2.0000],
        [5.0000, 9.0000, 9.0000, 6.0000]])
Difference after modification (X2_2 - X2): tensor([[0.5000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])
Difference after conversion to int: tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


## 2.3 Assignment 3

**Instruction**
1. Create a random **float** tensor `X3` of shape `(3, 2)`.
2. **Transpose** it to get shape `(2, 3)`.
3. Perform **matrix multiplication** of `X3 @ X3_transposed`.
4. Print the resulting **shape**.


In [14]:
# Assignment 3
X3 = torch.randn(3, 2)
X3_transposed = X3.T  # shape (2, 3)

result = X3 @ X3_transposed
print("X3 shape:", X3.shape)
print("X3_transposed shape:", X3_transposed.shape)
print("Result shape:", result.shape)  # expected (3, 3)


X3 shape: torch.Size([3, 2])
X3_transposed shape: torch.Size([2, 3])
Result shape: torch.Size([3, 3])


## 2.4 Assignment 4

**Instruction**
1. Create two tensors `X4_A` and `X4_B` of shape `(2, 3)`, each with random integers in range `[1..5)`.
2. Compute:
   - `X4_A + X4_B` (element-wise addition)
   - `X4_A - X4_B` (element-wise subtraction)
   - `X4_A * X4_B` (element-wise multiplication)
   - Print each result and **shape**.


In [15]:
# Assignment 4
X4_A = torch.randint(low=1, high=5, size=(2, 3))
X4_B = torch.randint(low=1, high=5, size=(2, 3))

add_res = X4_A + X4_B
sub_res = X4_A - X4_B
mul_res = X4_A * X4_B

print("X4_A:", X4_A, "shape:", X4_A.shape)
print("X4_B:", X4_B, "shape:", X4_B.shape)

print("\nX4_A + X4_B:", add_res, "shape:", add_res.shape)
print("\nX4_A - X4_B:", sub_res, "shape:", sub_res.shape)
print("\nX4_A * X4_B:", mul_res, "shape:", mul_res.shape)


X4_A: tensor([[2, 4, 2],
        [2, 1, 2]]) shape: torch.Size([2, 3])
X4_B: tensor([[1, 1, 2],
        [4, 4, 4]]) shape: torch.Size([2, 3])

X4_A + X4_B: tensor([[3, 5, 4],
        [6, 5, 6]]) shape: torch.Size([2, 3])

X4_A - X4_B: tensor([[ 1,  3,  0],
        [-2, -3, -2]]) shape: torch.Size([2, 3])

X4_A * X4_B: tensor([[2, 4, 4],
        [8, 4, 8]]) shape: torch.Size([2, 3])


## 2.5 Assignment 5

**Instruction**
1. Create a tensor `X5` of shape `(3, 4)` with `torch.linspace(1, 12, steps=12)` and then reshape it.
2. **Flatten** `X5` into 1D.
3. Print both the original shape and the flattened shape.


In [19]:
# Assignment 5
print(torch.linspace(1, 12, steps=12))
X5 = torch.linspace(1, 12, steps=12).reshape(3, 4)
X5_flat = X5.flatten()
print("X5:", X5)
print("X5_flat=",X5_flat)

print("X5 shape:", X5.shape)
print("X5_flat shape:", X5_flat.shape)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
X5: tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
X5_flat= tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
X5 shape: torch.Size([3, 4])
X5_flat shape: torch.Size([12])


## 2.6 Assignment 6

**Instruction**
1. Create a random float tensor `X6` of shape `(4, 4)`.
2. Compute the **column-wise sum** and the **row-wise sum**.
3. Print both results and confirm their shapes are `(4,)`.


In [20]:
# Assignment 6
X6 = torch.randn(3, 4)

col_sum = X6.sum(dim=0)  # column-wise
row_sum = X6.sum(dim=1)  # row-wise

print("X6:", X6)
print("\nColumn-wise sum:", col_sum, "shape:", col_sum.shape)
print("Row-wise sum:", row_sum, "shape:", row_sum.shape)


X6: tensor([[ 2.1010,  1.4371, -1.2776, -0.6300],
        [ 0.2694,  0.7482, -1.3798,  1.1960],
        [-0.1731, -0.8167,  0.1210, -0.7272]])

Column-wise sum: tensor([ 2.1974,  1.3687, -2.5364, -0.1612]) shape: torch.Size([4])
Row-wise sum: tensor([ 1.6306,  0.8339, -1.5961]) shape: torch.Size([3])


## 2.7 Assignment 7

**Instruction**
1. Create two random float tensors `X7_A` and `X7_B` each of shape `(2, 2)`.
2. **Concatenate** them along dimension `0` ⇒ result shape `(4, 2)`.
3. **Concatenate** them along dimension `1` ⇒ result shape `(2, 4)`.
4. Print both results.


In [21]:
# Assignment 7
X7_A = torch.randn(2, 2)
X7_B = torch.randn(2, 2)

cat_dim0 = torch.cat([X7_A, X7_B], dim=0)  # (4,2)
cat_dim1 = torch.cat([X7_A, X7_B], dim=1)  # (2,4)

print("X7_A:", X7_A)
print("X7_B:", X7_B)

print("\nConcatenate along dim=0 (shape {}):\n{}".format(tuple(cat_dim0.shape), cat_dim0))
print("\nConcatenate along dim=1 (shape {}):\n{}".format(tuple(cat_dim1.shape), cat_dim1))


X7_A: tensor([[ 1.9706,  0.1298],
        [ 0.8228, -0.8046]])
X7_B: tensor([[-0.3734,  0.1592],
        [ 1.0055, -0.5560]])

Concatenate along dim=0 (shape (4, 2)):
tensor([[ 1.9706,  0.1298],
        [ 0.8228, -0.8046],
        [-0.3734,  0.1592],
        [ 1.0055, -0.5560]])

Concatenate along dim=1 (shape (2, 4)):
tensor([[ 1.9706,  0.1298, -0.3734,  0.1592],
        [ 0.8228, -0.8046,  1.0055, -0.5560]])


## 2.8 Assignment 8

**Instruction**
1. Create a **3D random** tensor `X8` of shape `(2, 3, 4)` with `torch.randint`.
2. Compute the **maximum value** in the entire tensor.
3. Compute the **mean** along dimension `2`.
4. Print the shapes of the resulting tensors.


In [23]:
# Assignment 8
X8 = torch.randint(low=0, high=10, size=(2, 3, 4))  # integers
x8_max = X8.max()                                   # scalar
x8_mean_dim2 = X8.float().mean(dim=2)               # shape (2, 3)

print("X8 shape:", X8.shape)
print("Max value (scalar):", x8_max.item(), "shape:", x8_max.shape)
print("Mean along dim=2:", x8_mean_dim2)
print("Mean shape:", x8_mean_dim2.shape)
X8

X8 shape: torch.Size([2, 3, 4])
Max value (scalar): 9 shape: torch.Size([])
Mean along dim=2: tensor([[4.7500, 4.0000, 4.5000],
        [4.5000, 7.2500, 5.0000]])
Mean shape: torch.Size([2, 3])


tensor([[[4, 7, 6, 2],
         [2, 7, 1, 6],
         [5, 1, 9, 3]],

        [[7, 6, 5, 0],
         [8, 5, 8, 8],
         [6, 1, 5, 8]]])

## 2.9 Assignment 9

**Instruction**
1. Create a random float tensor `X9` of shape `(3, 3)`.
2. Compute the **determinant** of this matrix using `torch.linalg.det(X9)` (PyTorch 1.10+).
3. Print the result and interpret it (could be near zero if the matrix is nearly singular).


In [24]:
# Assignment 9
X9 = torch.randn(3, 3)
det_X9 = torch.linalg.det(X9)

print("X9:", X9)
print("\nDeterminant:", det_X9.item())

# Interpretation (basic):
# - If det is near 0, the matrix is close to singular (not invertible or numerically unstable to invert).
# - If det is far from 0, it's generally well-conditioned for inversion (not guaranteed, but a useful hint).


X9: tensor([[ 1.0935, -0.2637, -0.2296],
        [ 2.2003, -0.7842, -2.3885],
        [ 1.1878, -0.0755,  0.8630]])

Determinant: 0.13604314625263214


## 2.10 Assignment 10

**Instruction**
1. Create a random float tensor `X10` of shape `(3, 2)` using `torch.randn`.
2. Use `torch.stack` to replicate `X10` **3 times** along a **new dimension** ⇒ shape `(3, 3, 2)`.
3. Print the final shape.


In [25]:
# Assignment 10
X10 = torch.randn(3, 2)
X10_stacked = torch.stack([X10, X10, X10], dim=0)  # new dim at front => (3,3,2)

print("X10 shape:", X10.shape)
print("X10_stacked shape:", X10_stacked.shape)


X10 shape: torch.Size([3, 2])
X10_stacked shape: torch.Size([3, 3, 2])


---
### Done ✅
You now have a complete notebook for Assignments 1–10.
